### ISSUE TITLE
Feature request: Add `uniqueItems` validator for object arrays

### ISSUE THREAD

**Issue by justjam2013** [zahmo/ng-formworks#11]
**Detailed Description**
Currently you can add `"uniqueItems": true` as a validator for string arrays. This validates that all of the strings in the array are unique.
The suggested feature is to create a unique validator for object arrays, keyed off of string properties of the object.

**Context**
<-- Why is this change important to you? How would you use it? -->
I have a form for entering a list of devices. Each device must have a unique id and I would like to have a way to enforce that at the moment of creation, by blocking form submission.

<-- How can it benefit other users? -->
This allows validating that no two objects in an array are duplicates, based on a unique id. For example a list of employees could be unique over "firstName" + "lastName", or more likely a unique "employeeId". This would be useful in catching an error when there are a large number of entries, or when the id field might be longish, for example "99abbb69-dc5e-4b76-9b40-24aab4977c6d" and "99abbb69-dc5e-4b76-9b40-24abb4977c6d", where the only difference is a single character ("24aab" <-> "24abb").

**Possible Implementation**
```
{
  "schema": {
    "title": "Contextualized errors",
    "type": "array",
    "uniqueItems": ["employeeId"],
    "items": {
      "type": "object",
      "properties": {
        "employeeId": {
          "type": "string",
          "title": "Employee ID number"
        },
        "firstName": {
          "type": "string",
          "title": "First name"
        },
        "lastName": {
          "type": "string",
          "title": "Last name"
        }
      }
    }
  }
}
```

**Comment by zahmo** [comment]
Hi, currently there is a `uniqueItems` option available(`true`/`false`) as part of the [JSON Schema spec](https://json-schema.org/understanding-json-schema/reference/array#uniqueItems). The current behavior checks uniqueness for the entire array and not just on one field.For example if the employee ids are the same but their names are different, no error will be thrown, an error will only be thrown if all fields match exactly. Because validations can be so specific to the use case, it needs to be handled by the clients app, maybe by using the Forms `onSubmit` handler. But if you need to check uniqueness of only a one property schema, such as device id on its own, you could add  `"uniqueItems": true` to the schema,I've shared the demo [link](https://zahmo.github.io/ng-formworks/?set=ng-jsf&example=ng-jsf-flex-layout&framework=material-design&language=en&theme=demo-theme&formData=eyJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZW1wbG95ZWVzIjp7InR5cGUiOiJhcnJheSIsInVuaXF1ZUl0ZW1zIjp0cnVlLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJlbXBsb3llZUlkIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkVtcGxveWVlIElEIG51bWJlciJ9LCJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifX0sInJlcXVpcmVkIjpbImVtcGxveWVlSWQiXX19fX0sImxheW91dCI6W3sia2V5IjoiZW1wbG95ZWVzIiwiZGlzcGxheSI6ImZsZXgiLCJmbGV4LWZsb3ciOiJyb3cgd3JhcCIsInR5cGUiOiJhcnJheSIsImxpc3RJdGVtcyI6MywiaXRlbXMiOlt7InR5cGUiOiJkaXYiLCJkaXNwbGF5RmxleCI6dHJ1ZSwiZmxleC1kaXJlY3Rpb24iOiJyb3ciLCJpdGVtcyI6W3sia2V5IjoiZW1wbG95ZWVzW10uZW1wbG95ZWVJZCIsImZsZXgiOiIxIDEgOTBweCIsIm5vdGl0bGUiOmZhbHNlfSx7ImtleSI6ImVtcGxveWVlc1tdLmZpcnN0TmFtZSIsImZsZXgiOiI0IDQgMjAwcHgiLCJub3RpdGxlIjpmYWxzZX0seyJrZXkiOiJlbXBsb3llZXNbXS5sYXN0TmFtZSIsImZsZXgiOiI0IDQgMjAwcHgiLCJub3RpdGxlIjpmYWxzZX1dfV19XSwiZGF0YSI6eyJlbXBsb3llZXMiOlt7ImVtcGxveWVlSWQiOiIxMjMiLCJmaXJzdE5hbWUiOiJKYW5lIn0seyJlbXBsb3llZUlkIjoiMTIzIiwiZmlyc3ROYW1lIjoiSmFuZSJ9XX19) to the above employee case for you to test.
